# .github/workflows/caller-workflow.yml
name: Caller Workflow

on:
  push:
    branches:
      - master

jobs:
  trigger-callee-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Callee Workflow
      id: trigger_workflow
      uses: github.com/.github/workflows/callee-workflow.yml@master
      with:
        message: Greetings from the caller!
