# .github/workflows/caller-workflow.yml
name: Caller Workflow

on:
  push:
    branches:
      - master

jobs:
  call-workflow:
    uses: github.com/miteshjosys/callee-repo/.github/workflows/callee-workflow.yml@master
    with:
      message: Greetings from the caller!
